export const DEFAULT_THEME_CONFIG = {
  global: {},
  local: {}
};

export const ELEMENT_THEME_USER_CONFIG = 'ELEMENT_THEME_USER_CONFIG';

export const ELEMENT_THEME_PREVIEW_CONFIG = 'ELEMENT_THEME_PREVIEW_CONFIG';
