# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  assemble:
    docker:
      # specify the version you desire here
      - image: circleci/node:9.5-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # TODO run tests before deploy and docker build.

      - run:
          name: Assemble project
          command: yarn run deploy:build

  build:
    machine: true
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Build container with nginx for SPA application
          command: docker build -t tmconsulting/tmc24-components:develop .

  push:
    machine: true
    working_directory: ~/repo
    steps:
      - run:
          name: Login to the docker hub
          command: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run:
          name: Push image to registry
          command: docker push tmconsulting/tmc24-components:develop